queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - author=dependabot[bot]
      - label=dependencies
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    merge_conditions:
      - status-success=Pipeline Stack
      - status-success=Application Stacks
    merge_method: squash

pull_request_rules:
  - name: Automatically merge Dependabot PRs
    conditions:
      - base=main
      - author=dependabot[bot]
      - label=dependencies
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
      queue:
